### ISSUE TITLE
Is perflib a good idea?

### ISSUE THREAD

**Issue by jwenz723** [leoluk/perflib_exporter#4]
While trying to further understand how this exporter is working I stumbled across the following quote from [here](https://docs.microsoft.com/en-us/windows/desktop/perfctrs/using-the-registry-functions-to-consume-counter-data):

> You should not use the registry functions to consume counter data. Instead, you should use the Performance Data Helper (PDH) functions to consume counter data. The PDH functions are easier to use, oriented more towards operations on single counters rather than groups of counters, and can be used to access counter data from current activity or log files.

From what I understand, this is exactly what this application is doing. Wondering what response you have to this?

**Comment by leoluk** [comment]
In can confirm that I'm aware of that document (I think I even linked it somewhere) :-)

Writing a metrics exporter is one of the very few use cases where it's reasonable to use the registry API instead of PDH. PDH is a library designed for applications which present performance counters to users (like Windows Performance Monitor, which is itself using PDH), and takes care of all the hard work like scaling, formatting and sampling the values. If you use the registry API, you have to all of that yourself, hence the recommendation against its use.

However, we don't need any of the high-level feature PDH adds - we just need the raw counter values, and operating on groups of counters (or even "all of them") is perfect. We can get all counter values using a single RegQueryValueEx syscall and parse it ourselves without calling any external libraries.

telegraf includes a pdh binding, if you're curious: 

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/pdh.go#L284

Does this answer your question? Happy to elaborate further. Send me an email if you have any questions which don't fit into a bug tracker.

**Comment by jwenz723** [comment]
Ok, great. That answers my question. True, an email probably would have been better for this. Thanks.

**Comment by ofek** [comment]
Hey question: Microsoft claims PDH automatically uses Perflib when possible https://learn.microsoft.com/en-us/windows/win32/perfctrs/using-the-pdh-functions-to-consume-counter-data

Is that not accurate?

We're investigating why in some cases [PdhEnumObjects](https://learn.microsoft.com/en-us/windows/win32/api/pdh/nf-pdh-pdhenumobjectsa) takes an extremely long time.
