### ISSUE TITLE
Compare with metricbeat perfmon library?

### ISSUE THREAD

**Issue by rgl** [leoluk/perflib_exporter#5]
Hello,

First, hats off for creating this project, it seems pretty good! I've come here after being bitten by [wmi-exporter #89](https://github.com/martinlindhe/wmi_exporter/issues/89) and have some questions.

Did you investigate using the https://github.com/elastic/beats/tree/master/metricbeat/module/windows/perfmon library?

Was there a reason to use RegQueryValueEx instead of the PHD library (as in metricbeat)?

Is having [a configuration alike metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-windows-perfmon.html) more appropriate than trying to use object indices or deduce the metric names? Or is that not possible with RegQueryValueEx?

Thanks!

PS sorry if this is not the right place to ask questions.

**Comment by leoluk** [comment]
#4 answers some of your questions

**Comment by leoluk** [comment]
To elaborate some: the PDH library also uses `RegQueryValueEx` under the hood. perflib providers always return all metrics they have, much like Prometheus exporters, and PDH just picks from that. perflib_exporter skips that and just returns all metrics (with a single syscalls, so it's really fast).

That being said, having a hardcoded mapping like that or autogenerated code is definitely something I'm considering, but it's not entirely straight-forward due to different metrics being available on different systems/OS versions/3rd party providers.

**Comment by rgl** [comment]
Understood, thanks for the explanation!

**Comment by leoluk** [comment]
You're welcome! Feel free to send me an email or open an issue if you have any other questions.
